### PR TITLE
Update CAS from v1.1.0 to 1.1.1

### PR DESCRIPTION
**Pull request by dezande**
I need the `fetch_raw_info` for read attributes types list (see https://github.com/dlindahl/omniauth-cas/issues/47).
This feature is available in the project dlindahl/omniauth-cas master. I am merging this in this branch.

### CODE REVIEW

**Review by giniouxe — COMMENTED** [review]
The tests fail :slightly_smiling_face:

**Comment by dezande** [comment]
@giniouxe There are not circle CI configured. I don't know if we need for this project because we don't update every month.
Do you want to add a circle CI config?

**Comment by yannvery** [comment]
That's a lot of work to maintain the diff between this fork and the original repo.
I'm wondering if it's not the right time to stop it and going back to the official omniauth-cas repository.
What do you think @dezande?

**Comment by sebn** [comment]
What was the original reason for forking? (I'm not sure by looking at the commits)

**Comment by sebn** [comment]
> What was the original reason for forking?

Quoting @dezande (more or less):

The reason was the lack of SAML support. We could possibly get rid of the fork by handling it in the CAS strategy.

**Comment by dezande** [comment]
@giniouxe Test run well now

**Comment by dezande** [comment]
I test with
- ensma (cas saml). Problem with OmniAuth::module Strategies::CAS#fetch_raw_info line 223. Fixed with a get in saml_ticket_validator.
- usc (cas v2). No problem detected
- upm (cas v3). No problem detected

**Review by sebn — APPROVED** [review]

**Review by yannvery — APPROVED** [review]

**Pull request merged**
